---
title: 'Day 07: Camel Card'
author: "Ngan Ho"
date: "2023-12-07"
output: html_document
---

```{r setup, message=FALSE,include=FALSE}
library(stringr)
library(CELRPackage)
library(dplyr)
```

```{r echo=FALSE}
input = ReadExcelFiles("../DATA/Day07_CamelCards.xlsx")

input = input %>% 
  separate(col = "input",
           sep = " ",
           into = c("Hand", "Bid")) %>% 
  mutate(Bid = as.numeric(Bid))

cleaned_input = data.frame(do.call(rbind, strsplit(input$Hand, ""))) %>% 
  bind_cols(input) %>% 
  rename(Letter_1 = X1,
         Letter_2 = X2,
         Letter_3 = X3,
         Letter_4 = X4,
         Letter_5 = X5)
```

# Part 1

```{r echo=FALSE}
cards = c()
type = c()

for (i in 1:nrow(cleaned_input)) {
  
  card_df = tibble(
    '2'= 0,
    '3'= 0,
    "4"= 0,
    "5"= 0,
    "6"= 0,
    "7"= 0,
    "8"= 0,
    "9" = 0,
    "T" = 0,
    "J" = 0,
    "Q" = 0,
    "K" = 0,
    "A" = 0
  )
  
  
  hand_to_check = cleaned_input$Hand[i]
  card_on_hand = strsplit(hand_to_check, split="")[[1]]
  
  for (card in card_on_hand) {
    
    card_df = card_df %>% 
      mutate(across(contains(card), ~ .x + 1))
    
  }
  
  card_type_to_transfer = as.character(as.vector(card_df[1,]))
  
  dummy_type = tibble(
    'n_1' = 0,
    "n_2" = 0,
    "n_3" = 0,
    "n_4" = 0,
    "n_5" = 0
  )
  
  for (point in card_type_to_transfer) {
    
    dummy_type = dummy_type %>% 
      mutate(across(contains(point), ~ .x + 1))
    
  }
  
  dummy_type = dummy_type %>% 
    # pivot_longer(cols = everything(),
    #              names_to = "n_appear",
    #              values_to = "Point") %>% 
    mutate(Type = case_when(n_5 == 1 ~ "Five of a kind",
                            n_4 == 1 ~ "Four of a kind",
                            n_3 == 1 & n_2 == 1 ~ "Full house",
                            n_3 == 1 & n_2 != 1 ~ "Three of a kind",
                            n_2 == 2 ~ "Two pair",
                            n_2 == 1 & n_3 != "1" ~ "One pair",
                            T ~ "High card"))
  
  cards = append(cards, hand_to_check)
  type = append(type, dummy_type$Type)
  
}
  
type_df = tibble(
  'Hand' = cards,
  'Type' = type,
)

  


```


```{r echo=FALSE}
hand_with_type = cleaned_input %>% 
  left_join(type_df, by = "Hand") %>% 
  mutate(across(contains("Letter"), ~ case_when(.x == "2" ~ 1,
                                        .x == "3" ~ 2,
                                        .x == "4" ~ 3,
                                        .x == "5" ~ 4,
                                        .x == "6" ~ 5,
                                        .x == "7" ~ 6,
                                        .x == "8" ~ 7,
                                        .x == "9" ~ 8,
                                        .x == "T" ~ 9,
                                        .x == "J" ~ 10,
                                        .x == "Q" ~ 11,
                                        .x == "K" ~ 12,
                                        .x == "A" ~ 13)),
         Type = factor(Type,
                       levels=c("High card", "One pair", "Two pair", "Three of a kind", "Full house", "Four of a kind", "Five of a kind")))


hand_with_type <- hand_with_type[order(hand_with_type$Type, hand_with_type$Letter_1, hand_with_type$Letter_2, hand_with_type$Letter_3,
                                 hand_with_type$Letter_4, hand_with_type$Letter_5), ]

hand_with_type$Rank <- 1:nrow(hand_with_type)

hand_with_type = hand_with_type %>% 
  mutate(Multiply = Bid*Rank)





```


# Part 2

```{r echo=FALSE}
cards = c()
type = c()

for (i in 1:nrow(cleaned_input)) {
  
  card_df = tibble(
    '2'= 0,
    '3'= 0,
    "4"= 0,
    "5"= 0,
    "6"= 0,
    "7"= 0,
    "8"= 0,
    "9" = 0,
    "T" = 0,
    "J" = 0,
    "Q" = 0,
    "K" = 0,
    "A" = 0
  )
  
  
  hand_to_check = cleaned_input$Hand[i]
  card_on_hand = strsplit(hand_to_check, split="")[[1]]
  
  for (card in card_on_hand) {
    
    card_df = card_df %>% 
      mutate(across(contains(card), ~ .x + 1))
    
  }
  
  card_df = card_df %>% 
    mutate(value_to_add = ifelse(J != 0, J, 0),
           J = ifelse(J != 0, 0, J)) %>% 
    pivot_longer(cols = !value_to_add,
                 names_to = "Card",
                 values_to = "n") %>% 
    mutate(order_to_add = 1:13,
           is_max = case_when(n == max(n) ~ T,
                              T ~ F)) %>% 
    group_by(is_max) %>% 
    mutate(is_first = case_when(order_to_add == min(order_to_add) ~ T,
                                T ~ F)) %>% 
    ungroup() %>% 
    mutate(n = case_when(n == max(n) & is_first == T ~ n + value_to_add,
                         T ~ n)) %>% 
    select(-value_to_add, -order_to_add, -is_max, -is_first) %>%
    pivot_wider(names_from = "Card",
                values_from = "n")

  card_type_to_transfer = as.character(as.vector(card_df[1,]))
  
  dummy_type = tibble(
    'n_1' = 0,
    "n_2" = 0,
    "n_3" = 0,
    "n_4" = 0,
    "n_5" = 0
  )
  
  for (point in card_type_to_transfer) {
    
    dummy_type = dummy_type %>% 
      mutate(across(contains(point), ~ .x + 1))
    
  }
  
  dummy_type = dummy_type %>% 
    # pivot_longer(cols = everything(),
    #              names_to = "n_appear",
    #              values_to = "Point") %>% 
    mutate(Type = case_when(n_5 == 1 ~ "Five of a kind",
                            n_4 == 1 ~ "Four of a kind",
                            n_3 == 1 & n_2 == 1 ~ "Full house",
                            n_3 == 1 & n_2 != 1 ~ "Three of a kind",
                            n_2 == 2 ~ "Two pair",
                            n_2 == 1 & n_3 != "1" ~ "One pair",
                            T ~ "High card"))
  
  cards = append(cards, hand_to_check)
  type = append(type, dummy_type$Type)
  
}
  
type_df_2 = tibble(
  'Hand' = cards,
  'Type' = type,
)

  


```


```{r echo=FALSE}
hand_with_type_2 = cleaned_input %>% 
  left_join(type_df_2, by = "Hand") %>% 
  mutate(across(contains("Letter"), ~ case_when(
                                        .x == "J" ~ 1,
                                        .x == "2" ~ 2,
                                        .x == "3" ~ 3,
                                        .x == "4" ~ 4,
                                        .x == "5" ~ 5,
                                        .x == "6" ~ 6,
                                        .x == "7" ~ 7,
                                        .x == "8" ~ 8,
                                        .x == "9" ~ 9,
                                        .x == "T" ~ 10,
                                        .x == "Q" ~ 11,
                                        .x == "K" ~ 12,
                                        .x == "A" ~ 13)),
         Type = factor(Type,
                       levels=c("High card", "One pair", "Two pair", "Three of a kind", "Full house", "Four of a kind", "Five of a kind")))


hand_with_type_2 <- hand_with_type_2[order(hand_with_type_2$Type, hand_with_type_2$Letter_1, hand_with_type_2$Letter_2, hand_with_type_2$Letter_3,
                                 hand_with_type_2$Letter_4, hand_with_type_2$Letter_5), ]

hand_with_type_2$Rank <- 1:nrow(hand_with_type_2)

hand_with_type_2 = hand_with_type_2 %>% 
  mutate(Multiply = Bid*Rank)





```










































































